language: python
sudo: required
dist: xenial
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
env:
  - MARSHMALLOW_VERSION='2.13.*' FLASK_VERSION='0.10.*'
  - MARSHMALLOW_VERSION='2.14.*' FLASK_VERSION='0.11.*'
  - MARSHMALLOW_VERSION='2.15.*' FLASK_VERSION='0.12.*'
  - MARSHMALLOW_VERSION='2.15.*' FLASK_VERSION='1.0.*'
  - MARSHMALLOW_VERSION='3.0.0rc5' FLASK_VERSION='1.0.*'
install:
  - pip install -U pip
  - pip install Flask==$FLASK_VERSION
  - pip install marshmallow==$MARSHMALLOW_VERSION
  # Updating black?  Run pre-commit autoupdate to ref latest version in .pre-commit-config.yaml and keep in sync
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install black==19.3b0; fi
  - pip install '[.dev]'
  - pip freeze
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --check --diff .; fi && pytest
branches:
  only:
    # This prevents double building for a PR
    - master
    # Aso build on version tags matching this super basic version regex.
    - /^v\d+.*$/
jobs:
  include:
    - stage: release
      python: '3.7'
      env: skip
      script: skip
      install: skip

      deploy:
        provider: pypi
        user: plangrid
        password:
          secure: BxQ7V0aLIY3+22usLrk3d6sejNPekfYwRGxt2wDdbKKwI6vUK8h1FgigDKhsqfAAfXgr9q2LDYkj6C7/4dn34Ra6HFQ/3mZEVyQCfoBk26syYqkhWEg1lIkt8gr4xt/NfeIuVEQgH885casAt7lYCI2tHsGSLveCHHjNaYG7kcqSvcSlWgjv8EKyXRliRvZYNr1Br+vRAAkvUqyqG2WYm6l1QSojCrrWe6MheWv+SrO1s/X1TnCNXWONTU/Z/Ke2lx9so/87Q8T1P0Q34e1SG8naCvpMEx4uTkfwqjNGJtUAWIdyHMdmyuVQWFyoJ6K5rS4XQ74SYTb/xv12cPCoNUfmw4SoaCNEtU60zZ+Pt48SbaVD1i2opYx0C7VcS8B2s9tFh1roC+H+nHXhW79bENdI8F0FTXvFk9NN3C/b0JbFolju2EcwuRIrebD9GgOhSHpmQ2rLRKLvX6YEC0qYhdEFzg8l2Jc8YlivafNyoVemTJDnSOaH+b3y1d6WB1PEZFDqsaAgcz35BKMEfh+s8NbCyd/FcChaGxvFtHHg1+bipumRcsb/HgvM38OnHNA+Nfs6MWEx08RItv06tXFV768qNe8RfJajIcTlPOR+60fx4Uam1r6dEcRNc7EsgWVu4fkrpxtxQtTQfcnqwLAcDTOgcDmxGysxKM9zvI6dQww=
        on:
          tags: true
