language: python
sudo: required
dist: xenial
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
env:
  - MARSHMALLOW_VERSION='2.13.*' FLASK_VERSION='0.10.*' WERKZEUG_VERSION='0.16.1'
  - MARSHMALLOW_VERSION='2.14.*' FLASK_VERSION='0.11.*' WERKZEUG_VERSION='0.16.1'
  - MARSHMALLOW_VERSION='2.15.*' FLASK_VERSION='0.12.*' WERKZEUG_VERSION='0.16.1'
  - MARSHMALLOW_VERSION='2.15.*' FLASK_VERSION='1.0.*' WERKZEUG_VERSION='0.*'
  - MARSHMALLOW_VERSION='2.16.*' FLASK_VERSION='1.0.*' WERKZEUG_VERSION='0.*'
  - MARSHMALLOW_VERSION='2.17.*' FLASK_VERSION='1.0.*' WERKZEUG_VERSION='0.*'
  - MARSHMALLOW_VERSION='2.18.*' FLASK_VERSION='1.0.*' WERKZEUG_VERSION='0.*'
  - MARSHMALLOW_VERSION='2.19.*' FLASK_VERSION='1.0.*' WERKZEUG_VERSION='0.*'
  - MARSHMALLOW_VERSION='2.20.*' FLASK_VERSION='1.*' WERKZEUG_VERSION='1.*'
  - MARSHMALLOW_VERSION='3.0.0rc5' FLASK_VERSION='1.*' WERKZEUG_VERSION='1.*'
install:
  - pip install -U pip
  - pip install Flask==$FLASK_VERSION werkzeug==$WERKZEUG_VERSION marshmallow==$MARSHMALLOW_VERSION
  # Updating black?  Run pre-commit autoupdate to ref latest version in .pre-commit-config.yaml and keep in sync
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install black==19.3b0; fi
  - pip install '.[dev]'
  - pip freeze
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --check --diff .; fi && pytest
branches:
  only:
    # This prevents double building for a PR
    - master
    # Aso build on version tags matching this super basic version regex.
    - /^v\d+.*$/
jobs:
  include:
    - stage: release
      python: '3.7'
      env: skip
      script: skip
      install: skip

      deploy:
        distributions: "sdist bdist_wheel"
        provider: pypi
        user: plangrid
        password:
          secure: GoFaAo3a08PoPklGQ68q7EMYE59hb1Z1+PEMuSSXKelL2amyG6/kq5t7r8p6trjFabco1u94IwZFFlmUdfr4PqDQ/eaM9MVF1VvI8dxp/fg3WgSxjtxy4io/ELUWTGXTGs3V8Lp61haRdHjrqk5DwG6SHDVVzjuJBZ4Kydr6fuo0RWu9C4qAkU1MWmoIPeyeB4ZydXimD15uOvMp13UA7SqLUdXlAhwyL7c2h6pihu2gnbLXEnfkh8rlvRT8fSp7PUkFsg3FOvgMZg8dn8/J0I/pTmG7c71v0hacOVTKLsfAtSSHAjgcc8KffvMBOcE/YXgUr+lgR4R181lMqXv2LBNMuE5Gyc8GBjTb8Liiowpvg8XXH86vC/k+0/3toKWPobjsXJCAgR21+B7FFzE8hmZdP43HcSfCqbzS8ELUWF9AvUBlFtdakr0a0wLjcKsJyBNiKwwmw50kKsb7agpIXgS/I0Y6EyGwyXi8/q7IPmR7wffg3bAGnvvg5yz7vOZTGYJnFM+Ky1LdQ7fJ44D+Ze/SraB1syK2pmednX6YVMgIlPU5QpaprmQ9AkeoWmPZBShWl07Js73BnbQKWklkV8yAXq9qy51cjRA9SWQIFzeiHScOwhUalb1CpggOyG1sx4/GMFLg5nNE0ldKDfqUGJ4kbcNh25jiiBEJ7mEQkB0=
        on:
          branch: master
          tags: true
